### ISSUE TITLE
How just inferencing an image and show the result?

### ISSUE THREAD

**Issue by nmber5** [jiaxiZeng/Temporally-Consistent-Stereo-Matching#1]
as the tiltle.

**Comment by jiaxiZeng** [comment]
Hi, do you mean the single-frame mode of the model ?

**Comment by jiaxiZeng** [comment]
You can load your images and set the params = None for single-frame inference, and save the disp_pr as jet colormap:
```
with autocast(enabled=mixed_prec):
                testing_output = model(image1, image2, iters=iters, test_mode=True, params=None)
disp_pr = -testing_output['flow']
disp_pr = padder.unpad(disp_pr)
logFeatureMap(disp_pr[0], 'disp_out', wandb, vmin=0, vmax=192, cmap='jet', kitti_style=False, local_save=True, name='disp'):
```
logFeatureMap is in core/utils
/visualization.py, you can find the disparity map in "./localSave/disp_out/disp.png"

**Comment by nmber5** [comment]
thanks a lot.
i mean, a single pair of images, ie. [left_img, right_img]
