### ISSUE TITLE
Loading Pth file errors

### ISSUE THREAD

**Issue by CCamouflage-Hvv** [jiaxiZeng/Temporally-Consistent-Stereo-Matching#3]
Thanks for ur great work!

When I wanna use the .pth files in Dropbox, I encounter some problem.
Here are details:
` model.load_state_dict(checkpoint['model'], strict=True)
  File "envs\tcsm\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TCStereo:
        Missing key(s) in state_dict: "cnet.norm1.weight", "cnet.norm1.bias", "cnet.norm1.running_mean", "cnet.norm1.running_var", "cnet.layer1.0.norm1.weight", "cnet.layer1.0.norm1.bias", "cnet.layer1.0.norm1.running_mean", "cnet.layer1.0.norm1.running_var", "cnet.layer1.0.norm2.weight", "cnet.layer1.0.norm2.bias", "cnet.layer1.0.norm2.running_mean", "cnet.layer1.0.norm2.running_var", "cnet.layer1.1.norm1.weight", "cnet.layer1.1.norm1.bias", "cnet.layer1.1.norm1.running_mean", "cnet.layer1.1.norm1.running_var", "cnet.layer1.1.norm2.weight", "cnet.layer1.1.norm2.bias", "cnet.layer1.1.norm2.running_mean", "cnet.layer1.1.norm2.running_var", "cnet.layer2.0.norm1.weight", "cnet.layer2.0.norm1.bias", "cnet.layer2.0.norm1.running_mean", "cnet.layer2.0.norm1.running_var", "cnet.layer2.0.norm2.weight", "cnet.layer2.0.norm2.bias", "cnet.layer2.0.norm2.running_mean", "cnet.layer2.0.norm2.running_var", "cnet.layer2.0.norm3.weight", "cnet.layer2.0.norm3.bias", "cnet.layer2.0.norm3.running_mean", "cnet.layer2.0.norm3.running_var", "cnet.layer2.0.downsample.1.weight", "cnet.layer2.0.downsample.1.bias", "cnet.layer2.0.downsample.1.running_mean", "cnet.layer2.0.downsample.1.running_var", "cnet.layer2.1.norm1.weight", "cnet.layer2.1.norm1.bias", "cnet.layer2.1.norm1.running_mean", "cnet.layer2.1.norm1.running_var", "cnet.layer2.1.norm2.weight", "cnet.layer2.1.norm2.bias", "cnet.layer2.1.norm2.running_mean", "cnet.layer2.1.norm2.running_var", "cnet.layer3.0.norm1.weight", "cnet.layer3.0.norm1.bias", "cnet.layer3.0.norm1.running_mean", "cnet.layer3.0.norm1.running_var", "cnet.layer3.0.norm2.weight", "cnet.layer3.0.norm2.bias", "cnet.layer3.0.norm2.running_mean", "cnet.layer3.0.norm2.running_var", "cnet.layer3.0.norm3.weight", "cnet.layer3.0.norm3.bias", "cnet.layer3.0.norm3.running_mean", "cnet.layer3.0.norm3.running_var", "cnet.layer3.0.downsample.1.weight", "cnet.layer3.0.downsample.1.bias", "cnet.layer3.0.downsample.1.running_mean", "cnet.layer3.0.downsample.1.running_var", "cnet.layer3.1.norm1.weight", "cnet.layer3.1.norm1.bias", "cnet.layer3.1.norm1.running_mean", "cnet.layer3.1.norm1.running_var", "cnet.layer3.1.norm2.weight", "cnet.layer3.1.norm2.bias", "cnet.layer3.1.norm2.running_mean", "cnet.layer3.1.norm2.running_var", "cnet.layer4.0.norm1.weight", "cnet.layer4.0.norm1.bias", "cnet.layer4.0.norm1.running_mean", "cnet.layer4.0.norm1.running_var", "cnet.layer4.0.norm2.weight", "cnet.layer4.0.norm2.bias", "cnet.layer4.0.norm2.running_mean", "cnet.layer4.0.norm2.running_var", "cnet.layer4.0.norm3.weight", "cnet.layer4.0.norm3.bias", "cnet.layer4.0.norm3.running_mean", "cnet.layer4.0.norm3.running_var", "cnet.layer4.0.downsample.1.weight", "cnet.layer4.0.downsample.1.bias", "cnet.layer4.0.downsample.1.running_mean", "cnet.layer4.0.downsample.1.running_var", "cnet.layer4.1.norm1.weight", "cnet.layer4.1.norm1.bias", "cnet.layer4.1.norm1.running_mean", "cnet.layer4.1.norm1.running_var", "cnet.layer4.1.norm2.weight", "cnet.layer4.1.norm2.bias", "cnet.layer4.1.norm2.running_mean", "cnet.layer4.1.norm2.running_var", "cnet.layer5.0.norm1.weight", "cnet.layer5.0.norm1.bias", "cnet.layer5.0.norm1.running_mean", "cnet.layer5.0.norm1.running_var", "cnet.layer5.0.norm2.weight", "cnet.layer5.0.norm2.bias", "cnet.layer5.0.norm2.running_mean", "cnet.layer5.0.norm2.running_var", "cnet.layer5.0.norm3.weight", "cnet.layer5.0.norm3.bias", "cnet.layer5.0.norm3.running_mean", "cnet.layer5.0.norm3.running_var", "cnet.layer5.0.downsample.1.weight", "cnet.layer5.0.downsample.1.bias", "cnet.layer5.0.downsample.1.running_mean", "cnet.layer5.0.downsample.1.running_var", "cnet.layer5.1.norm1.weight", "cnet.layer5.1.norm1.bias", "cnet.layer5.1.norm1.running_mean", "cnet.layer5.1.norm1.running_var", "cnet.layer5.1.norm2.weight", "cnet.layer5.1.norm2.bias", "cnet.layer5.1.norm2.running_mean", "cnet.layer5.1.norm2.running_var", "cnet.outputs08.0.0.norm1.weight", "cnet.outputs08.0.0.norm1.bias", "cnet.outputs08.0.0.norm1.running_mean", "cnet.outputs08.0.0.norm1.running_var", "cnet.outputs08.0.0.norm2.weight", "cnet.outputs08.0.0.norm2.bias", "cnet.outputs08.0.0.norm2.running_mean", "cnet.outputs08.0.0.norm2.running_var", "cnet.outputs08.1.0.norm1.weight", "cnet.outputs08.1.0.norm1.bias", "cnet.outputs08.1.0.norm1.running_mean", "cnet.outputs08.1.0.norm1.running_var", "cnet.outputs08.1.0.norm2.weight", "cnet.outputs08.1.0.norm2.bias", "cnet.outputs08.1.0.norm2.running_mean", "cnet.outputs08.1.0.norm2.running_var", "cnet.outputs16.0.0.norm1.weight", "cnet.outputs16.0.0.norm1.bias", "cnet.outputs16.0.0.norm1.running_mean", "cnet.outputs16.0.0.norm1.running_var", "cnet.outputs16.0.0.norm2.weight", "cnet.outputs16.0.0.norm2.bias", "cnet.outputs16.0.0.norm2.running_mean", "cnet.outputs16.0.0.norm2.running_var", "cnet.outputs16.1.0.norm1.weight", "cnet.outputs16.1.0.norm1.bias", "cnet.outputs16.1.0.norm1.running_mean", "cnet.outputs16.1.0.norm1.running_var", "cnet.outputs16.1.0.norm2.weight", "cnet.outputs16.1.0.norm2.bias", "cnet.outputs16.1.0.norm2.running_mean", "cnet.outputs16.1.0.norm2.running_var", "fnet.conv1.weight", "fnet.conv1.bias", "fnet.layer1.0.conv1.weight", "fnet.layer1.0.conv1.bias", "fnet.layer1.0.conv2.weight", "fnet.layer1.0.conv2.bias", "fnet.layer1.1.conv1.weight", "fnet.layer1.1.conv1.bias", "fnet.layer1.1.conv2.weight", "fnet.layer1.1.conv2.bias", "fnet.layer2.0.conv1.weight", "fnet.layer2.0.conv1.bias", "fnet.layer2.0.conv2.weight", "fnet.layer2.0.conv2.bias", "fnet.layer2.0.downsample.0.weight", "fnet.layer2.0.downsample.0.bias", "fnet.layer2.1.conv1.weight", "fnet.layer2.1.conv1.bias", "fnet.layer2.1.conv2.weight", "fnet.layer2.1.conv2.bias", "fnet.layer3.0.conv1.weight", "fnet.layer3.0.conv1.bias", "fnet.layer3.0.conv2.weight", "fnet.layer3.0.conv2.bias", "fnet.layer3.0.downsample.0.weight", "fnet.layer3.0.downsample.0.bias", "fnet.layer3.1.conv1.weight", "fnet.layer3.1.conv1.bias", "fnet.layer3.1.conv2.weight", "fnet.layer3.1.conv2.bias", "fnet.conv2.weight", "fnet.conv2.bias".
        Unexpected key(s) in state_dict: "conv2.0.conv1.weight", "conv2.0.conv1.bias", "conv2.0.conv2.weight", "conv2.0.conv2.bias", "conv2.1.weight", "conv2.1.bias".`

And my environment and OS:
**Windows
torch                     2.0.1+cu117
torchaudio                2.0.2+cu117
torchvision               0.15.2+cu117**

Is any update of network architecture?

**Comment by jiaxiZeng** [comment]
Hi, which .pth file and script did you use?

**Comment by jiaxiZeng** [comment]
It's ok for me to load the ckpt, you should check your code.

![image](https://github.com/user-attachments/assets/50a4869d-c155-4e76-a821-dc93c81e87ca)

**Comment by CCamouflage-Hvv** [comment]
I have found the mistake in my code.
Thank you!
