### ISSUE TITLE
How to reproduce the  temporal consistency results of table1 in the paper

### ISSUE THREAD

**Issue by yamal-shang** [jiaxiZeng/Temporally-Consistent-Stereo-Matching#4]
Thank you very much for your excellent work, I want to know how to reproduce the temporal consistency results. I use your tartanair pretrained model and warp function to warp the current disp to previous, but the |∆d| is bigger than table1 in the paper.

**Comment by jiaxiZeng** [comment]
Thank you for your interest in our work. We have uploaded the code for evaluating temporal consistency to the `temporal_consistency_eval `branch. You can evaluate temporal consistency using the `validate_tartanair `function in `evaluate_stereo.py`. Below are our evaluation results.
![image](https://github.com/user-attachments/assets/a6052dd1-47b3-42e9-8649-fad8fdebc898)
